In [ ]:
print("Hi")

Hi


In [ ]:
import numpy as np
A=np.array([[3,2,2],[2,3,-2]])

print("Original Array:",A)
u,s,vt=np.linalg.svd(A)
print("U:\n",u)
print("\nS:\n",s)
print("VT:\n",vt)
print("\nDiagonal :",np.diag(A))

Original Array: [[ 3  2  2]
 [ 2  3 -2]]
U:
 [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]

S:
 [5. 3.]
VT:
 [[-7.07106781e-01 -7.07106781e-01 -6.47932334e-17]
 [-2.35702260e-01  2.35702260e-01 -9.42809042e-01]
 [-6.66666667e-01  6.66666667e-01  3.33333333e-01]]

Diagonal : [3 3]


In [ ]:
from ucimlrepo import fetch_ucirepo
import matplotlib.pyplot as plt

# fetch dataset
heart_disease = fetch_ucirepo(id=45)

# data (as pandas dataframes)
X = heart_disease.data.features
y = heart_disease.data.targets

# metadata
print(heart_disease.metadata)

# variable information
print(heart_disease.variables)



{'uci_id': 45, 'name': 'Heart Disease', 'repository_url': 'https://archive.ics.uci.edu/dataset/45/heart+disease', 'data_url': 'https://archive.ics.uci.edu/static/public/45/data.csv', 'abstract': '4 databases: Cleveland, Hungary, Switzerland, and the VA Long Beach', 'area': 'Health and Medicine', 'tasks': ['Classification'], 'characteristics': ['Multivariate'], 'num_instances': 303, 'num_features': 13, 'feature_types': ['Categorical', 'Integer', 'Real'], 'demographics': ['Age', 'Sex'], 'target_col': ['num'], 'index_col': None, 'has_missing_values': 'yes', 'missing_values_symbol': 'NaN', 'year_of_dataset_creation': 1989, 'last_updated': 'Fri Nov 03 2023', 'dataset_doi': '10.24432/C52P4X', 'creators': ['Andras Janosi', 'William Steinbrunn', 'Matthias Pfisterer', 'Robert Detrano'], 'intro_paper': {'ID': 231, 'type': 'NATIVE', 'title': 'International application of a new probability algorithm for the diagnosis of coronary artery disease.', 'authors': 'R. Detrano, A. Jánosi, W. Steinbrunn, M

From the Online Retail prediction

In [ ]:
from ucimlrepo import fetch_ucirepo
import matplotlib.pyplot as plt


# fetch dataset
online_retail = fetch_ucirepo(id=352)

# data (as pandas dataframes)
X = online_retail.data.features
y = online_retail.data.targets

# metadata
print(online_retail.metadata)


# variable information
print(online_retail.variables)


{'uci_id': 352, 'name': 'Online Retail', 'repository_url': 'https://archive.ics.uci.edu/dataset/352/online+retail', 'data_url': 'https://archive.ics.uci.edu/static/public/352/data.csv', 'abstract': 'This is a transactional data set which contains all the transactions occurring between 01/12/2010 and 09/12/2011 for a UK-based and registered non-store online retail.', 'area': 'Business', 'tasks': ['Classification', 'Clustering'], 'characteristics': ['Multivariate', 'Sequential', 'Time-Series'], 'num_instances': 541909, 'num_features': 6, 'feature_types': ['Integer', 'Real'], 'demographics': [], 'target_col': None, 'index_col': ['InvoiceNo', 'StockCode'], 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 2015, 'last_updated': 'Mon Oct 21 2024', 'dataset_doi': '10.24432/C5BW33', 'creators': ['Daqing Chen'], 'intro_paper': {'ID': 361, 'type': 'NATIVE', 'title': 'Data mining for the online retail industry: A case study of RFM model-based customer segmenta

In [ ]:
from os import ST_NOSUID
import pandas as pd
import numpy as np
import scipy


import seaborn as sns
import matplotlib.pyplot as plt

df=pd.read_csv('/content/diabetes.csv')
# print(df.head())
# # print(df.info())
# print(df.sum())
max_val =np.max(np.abs(df))
max_val
print(max_val)
print("\nvalue:\n",((df-max_val)/max_val))

846.0

value:
      Pregnancies   Glucose  BloodPressure  SkinThickness   Insulin       BMI  \
0      -0.992908 -0.825059      -0.914894      -0.958629 -1.000000 -0.960284   
1      -0.998818 -0.899527      -0.921986      -0.965721 -1.000000 -0.968558   
2      -0.990544 -0.783688      -0.924350      -1.000000 -1.000000 -0.972459   
3      -0.998818 -0.894799      -0.921986      -0.972813 -0.888889 -0.966785   
4      -1.000000 -0.838061      -0.952719      -0.958629 -0.801418 -0.949054   
..           ...       ...            ...            ...       ...       ...   
763    -0.988180 -0.880615      -0.910165      -0.943262 -0.787234 -0.961111   
764    -0.997636 -0.855792      -0.917258      -0.968085 -1.000000 -0.956501   
765    -0.994090 -0.856974      -0.914894      -0.972813 -0.867612 -0.969031   
766    -0.998818 -0.851064      -0.929078      -1.000000 -1.000000 -0.964421   
767    -0.998818 -0.890071      -0.917258      -0.963357 -1.000000 -0.964066   

     DiabetesPedigreeFun

In [ ]:



import pandas as pd
from sklearn.preprocessing import MinMaxScaler

df = pd.read_csv('SampleFile.csv')
print(df.head())
import numpy as np
max_vals = np.max(np.abs(df))
max_vals
print((df - max_vals) / max_vals)

scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(df)
scaled_df = pd.DataFrame(scaled_data,
                         columns=df.columns)
scaled_df.head()

   LotArea  MSSubClass
0     8450          60
1     9600          20
2    11250          60
3     9550          70
4    14260          60
       LotArea  MSSubClass
0    -0.960742   -0.999721
1    -0.955400   -0.999907
2    -0.947734   -0.999721
3    -0.955632   -0.999675
4    -0.933750   -0.999721
...        ...         ...
1455 -0.963219   -0.999721
1456 -0.938791   -0.999907
1457 -0.957992   -0.999675
1458 -0.954856   -0.999907
1459 -0.953834   -0.999907

[1460 rows x 2 columns]


LotArea  MSSubClass
0  0.033420    0.235294
1  0.038795    0.000000
2  0.046507    0.235294
3  0.038561    0.294118
4  0.060576    0.235294

In [6]:
from  sklearn.preprocessing import StandardScaler
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
#from sklearn.decomposition import pca
data={
    'maths':[98,89,76,78,77],'tamil':[54,65,78,66,89]
}
df=pd.DataFrame(data)
scaler=StandardScaler()
scaled_data=scaler.fit_transform(df)
scaled_df=pd.DataFrame(scaled_data,columns=df.columns)
scaled_df.head()

maths     tamil
0  1.675779 -1.365529
1  0.628417 -0.449625
2 -0.884439  0.632806
3 -0.651692 -0.366361
4 -0.768065  1.548710